
////////////

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pro: <http://purl.org/spar/pro/>

SELECT DISTINCT
 ?person
 (GROUP_CONCAT(DISTINCT ?role ; separator = " ; ") AS ?rolelist)
 ?id
WHERE {
 ?person a foaf:Person ;
  pro:holdsRoleInTime ?role ;

}
GROUP BY ?person
LIMIT 10



////////
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pro: <http://purl.org/spar/pro/>
PREFIX rdsf: <http://www.w3.org/2000/01/rdf-schema>

SELECT DISTINCT
 ?person ?label ?givenName ?familyName
 (GROUP_CONCAT(DISTINCT ?role ; separator = " ; ") AS ?rolelist)
WHERE {
 ?person a foaf:Person ;
  foaf:givenName ?givenName;
  foaf:familyName ?familyName;
  pro:holdsRoleInTime ?role  .
}
GROUP BY ?person ?label ?givenName ?familyName
LIMIT 10


///PERSON

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pro: <http://purl.org/spar/pro/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
SELECT DISTINCT
 ?person ?label ?givenName ?familyName
 (GROUP_CONCAT(DISTINCT ?role ; separator = " ; ") AS ?roles)
(GROUP_CONCAT(DISTINCT ?relate; separator = " ; ") AS ?relates)
(GROUP_CONCAT(DISTINCT ?creator; separator = " ; ") AS ?creators)
(GROUP_CONCAT(DISTINCT ?coauthor; separator = " ; ") AS ?coauthors)
(GROUP_CONCAT(DISTINCT ?realization; separator = " ; ") AS ?realizations)
WHERE {
 ?person a foaf:Person ;
  foaf:givenName ?givenName;
  foaf:familyName ?familyName;
  rdfs:label ?label;

  pro:holdsRoleInTime ?role  .

 ?role pro:relatesToDocument ?relate .

 ?relate frbr:realization ?realization .

 ?relate frbr:creator ?creator .

 ?coauthor pro:relatesToDocument ?relate .



}
GROUP BY ?person ?label ?givenName ?familyName
LIMIT 10

////JournalArticle
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pro: <http://purl.org/spar/pro/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX cito: <http://purl.org/spar/cito/>
SELECT DISTINCT
?article ?title ?publicationYear
(GROUP_CONCAT(DISTINCT ?cito; separator = " ; ") AS ?cities)
WHERE {

?article a fabio:JournalArticle ;
      dcterms:title ?title ;
      fabio:hasPublicationYear ?publicationYear ;
      cito:cites ?cito .


}
GROUP BY ?article ?title ?publicationYear
LIMIT 10



/// last query used on data.json

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pro: <http://purl.org/spar/pro/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX fabio: <http://purl.org/spar/fabio/>
SELECT DISTINCT
 ?person
(GROUP_CONCAT(DISTINCT ?label; separator = " ; ") AS ?labelList)
(GROUP_CONCAT(DISTINCT ?givenName; separator = " ; ") AS ?givenNameList)
(GROUP_CONCAT(DISTINCT ?familyName; separator = " ; ") AS ?familyNameList)
(GROUP_CONCAT(DISTINCT ?coauthor; separator = " ; ") AS ?coauthorList)
(GROUP_CONCAT(DISTINCT ?publicationYear; separator = " ; ") AS ?publicationYearList)
WHERE {
 ?person a foaf:Person ;
  foaf:givenName ?givenName;
  foaf:familyName ?familyName;
  rdfs:label ?label;

  pro:holdsRoleInTime ?role  .

 ?role pro:relatesToDocument ?relate .

 ?relate frbr:realization ?realization .

 ?coauthor pro:relatesToDocument ?relate .

 ?realization a fabio:JournalArticle ;

fabio:hasPublicationYear ?publicationYear .



}
GROUP BY ?person